### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by gilbitron** [marcshilling/react-native-idle-timer#3]
Getting the following error on iOS:

```
undefined is not an object (evaluating '_reactNativeIdleTimer2.default.setIdleTimerDisabled')
```

**Comment by gilbitron** [comment]
Ignore me. I hadn't recompiled my Xcode project.

**Comment by anniewey** [comment]
Followed the installation guide completely and I'm getting this on Android. @marcshilling Any idea why?

```
import IdleTimerManager from "react-native-idle-timer";

componentDidMount() {
		console.log(IdleTimerManager); //prints undefined
}
```

"react-native": "^0.55.4",
"react-native-idle-timer": "^2.1.5"

**Comment by jameslouiz** [comment]
i found running `pod install` within the ios directory worked for me
