### ISSUE TITLE
Cannot read property 'setIdleTimerDisabled' of undefined on tvOS

### ISSUE THREAD

**Issue by abcd-ca** [marcshilling/react-native-idle-timer#5]
Hi @marcshilling, I got your library to work on iOS but I wonder if you have any suggestions for getting it to work on tvOS? I am getting, "Unhandled JS Exception: Cannot read property 'setIdleTimerDisabled' of undefined". I've tried adding the project to my project, manually. I've added the (tvOS compiled) .a to my linked libraries. In that view, if I right click the .a and Show in Finder, it does show me the file in the finder. Any ideas of what else I might be missing? Here's the commit I made. If we can get it working I'll issue a pull request: https://github.com/abcd-ca/react-native-idle-timer/commit/677541b9cd5a65f61c5333e713dd50a949221c31 Thanks!

**Comment by abcd-ca** [comment]
follow-up: It's something to do with the project configuration 'cause when I just copy the .h and .m into my project, the source code works as is

**Comment by marcshilling** [comment]
That error means you haven't linked the native library correctly. I'd recommend starting from scratch and following the README instructions again. Hard to tell without me looking at your project structure.
